In [44]:
import numpy as np

data_fig2b = np.load("fig2b_data.npz")
data_fig2a = np.load("fig2a_data.npz")

In [45]:
data_fig2a["DeltaG"]

array([13.81551056,  9.38483679,  7.66909684,  4.20055042,  2.88917125,
        1.7897516 ,  1.13123621,  0.47056645])

In [47]:
data_fig2a_test = np.load("results/2025-05-28_16-51-11+0100/simulation_results.npz")

In [54]:
print(data_fig2a_test["t_switching_asymmetry_mean"])
print(data_fig2a["t_switching_asymmetry"])

[nan nan nan nan nan nan nan nan]
[0.07973495 0.07914577 0.07881832 0.06952436 0.05566489 0.03782828
 0.02714578 0.01195879]


In [56]:
data = data_fig2a
import matplotlib.pyplot as plt
## Plotting section
fig, ax = plt.subplots(figsize=(6, 5))
ax.errorbar(
    data["DeltaG"],
    data["t_switching_mean"][0],
    yerr=data["t_switching_std"][0],
    fmt="o-",
    label=r"$\tau_+$",
    capsize=3,
    color="tab:red",
)
ax.errorbar(
    data["DeltaG"],
    data["t_switching_mean"][1],
    yerr=data["t_switching_std"][1],
    fmt="o-",
    label=r"$\tau_-$",
    capsize=3,
    color="tab:blue",
)

ax.set_xlabel(r"$\Delta G$")
ax.set_ylabel(r"Switching time $\tau_{\pm}$")
ax.legend()

fig.savefig("plots/fig2A_switching_times_vs_dG.png", dpi=300, bbox_inches="tight")
plt.close(fig)

## switching time
fig, ax = plt.subplots(figsize=(4, 3))
ax.errorbar(
    data["DeltaG"],
    data["t_switching_asymmetry"],
    yerr=data["t_switching_asymmetry_std"],
    fmt="o-",
    capsize=3,
    color="k",
)
ax.set_xlabel(r"$\Delta G$")
# ax.set_ylabel(r"Relative asymmetry")
ax.set_ylabel(r"$(\tau_--\tau_+)/\langle \tau\rangle$")
# ax.legend()


fig.savefig("plots/fig2A_switching_times_inset.png", dpi=300, bbox_inches="tight")
plt.close(fig)

In [22]:
len(data_fig2b["J"])

22

In [23]:
data_fig2cd = np.load("fig2cd_data.npz")
data_fig2cd.files

['J_list', 'epsilon_list', 'switching_time_asym', 'switching_dwell_ratio']

In [25]:
J_list = data_fig2cd["J_list"]
len(J_list)

11

In [26]:
epsilon_list = data_fig2cd["epsilon_list"]

In [27]:
len(epsilon_list)

13

In [28]:
fig4a = np.load("fig4a_data.npz")
fig4b = np.load("fig4b_data.npz")
fig5a = np.load("fig5a_data.npz")
fig5b = np.load("fig5b_data.npz")

In [29]:
fig4a.files

['inset_DeltaG',
 'inset_suceptibility',
 'main_eb',
 'main_DeltaG',
 'main_amplitude']

In [30]:
fig4a["main_eb"]

array([-0.5 , -0.4 , -0.3 , -0.2 , -0.1 , -0.05,  0.  ,  0.05,  0.1 ,
        0.2 ,  0.3 ,  0.4 ,  0.5 ])

In [31]:
fig4b.files

['amplitude_threshold', 'speed_threshold', 'J_list', 'epsilon_list', 'eb']

In [43]:
len(fig5b["DeltaG"])


6

In [39]:
fig5a["DeltaG"]

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8., 12., 16., 20.])